IYun/Controllers/TeaPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IYun.Models;
using Webdiyer.WebControls.Mvc;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using IYun.Controllers.ControllerObject;
using IYun.Object;
using IYun.Views.TeaPlan.ViewObject;
using Newtonsoft.Json;
using NPOI.HSSF.UserModel;
using NPOI.HSSF.Util;
using NPOI.SS.UserModel;
using NPOI.SS.Util;
using NPOI.XSSF.UserModel;
using System.Collections;
using System.Configuration;
using IYun.Common;
using System.Text;
using System.Web.Http;
using System.Web.Optimization;
using System.Web.Routing;
using static NPOI.HSSF.Util.HSSFColor;
using log4net;
using System.Reflection;

namespace IYun.Controllers
{
    /// <summary>
    /// 新教学计划管理
    /// </summary>
    public class TeaPlanController : AdminBaseController
    {
        // GET: /TeaPlan/
        public string TeaPlanInsert(string fileName)
        {
            var result = new ExcelDownDto() { IsOk = false, Message = "未知错误！" };
            string Hz; //后缀名
            using (FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read))
            {
                IWorkbook workbook;
                if (fileName.IndexOf(".xlsx", StringComparison.OrdinalIgnoreCase) > 0)
                {
                    workbook = new XSSFWorkbook(fs);
                    Hz = ".xlsx";
                }
                else if (fileName.IndexOf(".xls", StringComparison.OrdinalIgnoreCase) > 0)
                {
                    workbook = new HSSFWorkbook(fs);
                    Hz = ".xls";
                }
                else
                {
                    return JsonConvert.SerializeObject(result);
                }
                var sheet = workbook.GetSheetAt(0);
                if (sheet == null)
                {
                    return JsonConvert.SerializeObject(result);
                }
                var list = new List<ls>(); //集合

                for (int i = 1; i < sheet.PhysicalNumberOfRows; i++)
                {
                    var kc = "";
                    var zy = 0;
                    var zx = 0;
                    var ismain = "";
                    var kclx = "";
                    var row = sheet.GetRow(i);
                    if (row == null)
                    {
                        continue;
                    }
                    for (int j = 0; j < 15; j++)
                    {
                        var cell = row.GetCell(j);

                        #region 针对行操作

                        switch (j)
                        {
                            case 0:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    kc = cell.StringCellValue.Trim();
                                }
                                break;
                            case 1:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    zy = Convert.ToInt32(cell.NumericCellValue);
                                }
                                break;
                            case 2:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    zx = Convert.ToInt32(cell.NumericCellValue);
                                }
                                break;

                            case 13:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    ismain = cell.StringCellValue.Trim();
                                }
                                break;
                            case 14:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    kclx = cell.StringCellValue.Trim();
                                }
                                break;

                            case 3:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    var data = new ls
                                    {
                                        kc = kc,
                                        zyks = zy,
                                        zxks = zx,
                                        kctype = kclx,
                                        zgisok = ismain,
                                        term = 1,
                                        msks = Convert.ToInt32(cell.NumericCellValue)
                                    };
                                    list.Add(data);
                                }
                                break;
                            case 4:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    var data = new ls
                                    {
                                        kc = kc,
                                        zyks = zy,
                                        zxks = zx,
                                        kctype = kclx,
                                        zgisok = ismain,
                                        term = 2,
                                        msks = Convert.ToInt32(cell.NumericCellValue)
                                    };
                                    list.Add(data);
                                }
                                break;
                            case 5:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    var data = new ls
                                    {
                                        kc = kc,
                                        zyks = zy,
                                        zxks = zx,
                                        kctype = kclx,
                                        zgisok = ismain,
                                        term = 3,
                                        msks = Convert.ToInt32(cell.NumericCellValue)
                                    };
                                    list.Add(data);
                                }
                                break;
                            case 6:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    var data = new ls
                                    {
                                        kc = kc,
                                        zyks = zy,
                                        zxks = zx,
                                        kctype = kclx,
                                        zgisok = ismain,
                                        term = 4,
                                        msks = Convert.ToInt32(cell.NumericCellValue)
                                    };
                                    list.Add(data);
                                }
                                break;
                            case 7:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    var data = new ls
                                    {
                                        kc = kc,
                                        zyks = zy,
                                        zxks = zx,
                                        kctype = kclx,
                                        zgisok = ismain,
                                        term = 5,
                                        msks = Convert.ToInt32(cell.NumericCellValue)
                                    };
                                    list.Add(data);
                                }
                                break;
                            case 8:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    var data = new ls
                                    {
                                        kc = kc,
                                        zyks = zy,
                                        zxks = zx,
                                        kctype = kclx,
                                        zgisok = ismain,
                                        term = 6,
                                        msks = Convert.ToInt32(cell.NumericCellValue)
                                    };
                                    list.Add(data);
                                }
                                break;
                            case 9:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    var data = new ls
                                    {
                                        kc = kc,
                                        zyks = zy,
                                        zxks = zx,
                                        kctype = kclx,
                                        zgisok = ismain,
                                        term = 7,
                                        msks = Convert.ToInt32(cell.NumericCellValue)
                                    };
                                    list.Add(data);
                                }
                                break;
                            case 10:
                                if (cell.CellType != CellType.BLANK) //判断是否为空
                                {
                                    var data = new ls
                                    {

IYun/Views/TeaPlan/IsMainCoursePlanClass.cshtml
@{
    Layout = null;
}
@using System.Configuration
@using IYun.Models
@using IYun.Object
@model List<IYun.Controllers.ControllerObject.CoursePlanDto>
@{
    Layout = null;
    var modulePowers = ViewBag.modulePowers as List<ModulePower>;
    modulePowers = modulePowers ?? new List<ModulePower>();
    var year = Convert.ToInt32(ViewData["year"]);
    var school = Convert.ToInt32(ViewData["school"]);

    var list = Model.GroupBy(u => new
    {
        u.y_year,
        u.majorName,
        u.stuTypeName,
        u.eduTypeName,
        u.rs
    }).ToList();

}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ConfigurationManager.AppSettings["SchoolTitle"]</title>
    <link rel="stylesheet" href="~/Content/manage/style/css.css?v=1" type="text/css" /><!-- 全部样式 -->
    <link rel="stylesheet" href="~/Content/manage/style/reset.css" type="text/css" /><!-- 重置样式 -->
    <link href="~/Content/manage/style/pic.css" rel="stylesheet" type="text/css" /><!-- 相册样式 -->
    <!--[ifltIE9]>
    <script type="text/javascript" src="js/html5shiv.js"></script>
    <![endif]-->
    <!-- 使得ie678支持HTML5标签 -->
    <!--[ifltIE10]> 
    <script type="text/javascript" src="~/Content/manage/js/PIE.js"></script>
    <![endif]-->
    <!-- 使得ie6789支持CSS3样式 -->
    @*<script src="~/Content/manage/js/jquery-1.7.1.min.js" type="text/javascript"></script>*@
    <script src="~/Content/js/jquery-1.9.1.min.js"></script>
    <script src="~/Content/manage/js/jquery.nicescroll.js" type="text/javascript"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/respond.js"></script>
    <script src="~/Content/manage/ComboboxBind.js?v=1"></script>  
    <script src="~/Content/EasyUI/easyloader.js"></script>
    <link href="~/Content/EasyUI/combo.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/combobox.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/panel.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/textbox.css" rel="stylesheet" />
    <script type="text/javascript">
        //EvPNG.fix('div, ul, img, li, input');

        $(function() {
            if (window.PIE) {
                $('.rounded').each(function() {
                    PIE.attach(this);
                });
            }
            //使得ie6789支持CSS3样式

        });

    </script>
    <style>
        .xx-table td {
            border: 1px solid #e9e9e9;
        }
    </style>
</head>

<body>
    @Html.Action("Top", "AdminBase")
    <div class="main center">
        <div id="main-tl">
            <div class="left-t">教务管理</div>
            <div class="left-c">
                @{
                    foreach (var modulePower in modulePowers)
                    {
                        if (modulePower.y_url.ToLower() == "/TeaPlan/IsMainCoursePlan".ToLower())
                        {
                            <a class="on" href="@modulePower.y_url">@modulePower.y_moudleName</a>
                        }
                        else
                        {
                            <a href="@modulePower.y_url">@modulePower.y_moudleName</a>
                        }
                    }
                }
            </div>
        </div>
        <div id="main-tr">
            <form action="@Url.Action("IsMainCoursePlanClass","TeaPlan")" id="searchForm" method="post">
                <div class="cli">
                    <div class="zc-inn">
                        <span style="margin-left: 20px;">年度</span>
                        @Html.Action("EnrollYear2", "Helper", new HelperParameterM { style = "width:200px;font-size: 18px;", index = year })
                    </div>
                    <div class="zc-inn">
                        <span style="margin-left: 20px;">函授站</span>
                        @Html.Action("SubSchool", "Helper", new HelperParameterM { className = "easyui-combobox" })
                    </div>
                    <div class="zc-head">
                        <input style="margin-top: 10px; height: 32px; line-height: 30px; float: right" class="cx-sub" type="button" onclick="ExcelDown()" value="导出" />
                        <input style="margin-top: 10px; height: 32px; line-height: 30px; float: right" class="cx-sub" type="submit" value="查找" />
                    </div>
                </div>
            </form>

            <table class="xx-table ydong-tab">
                <tr>
                    <th>年度</th>
                    <th>专业名</th>
                    <th>层次</th>
                    <th>形式</th>
                    <th>人数</th>
                    <th>学期</th>
                    <th>主干课程</th>
                </tr>

                @foreach (var item in list)
                {
                    var lists = item.ToList();
                    var count = item.Count();
                    var teamcount = lists.Count(u => u.y_team == lists[0].y_team);
                    var secordcount = count - teamcount;

                    <tr>
                        <td rowspan="@count">@item.Key.y_year</td>
                        <td rowspan="@count">@item.Key.majorName</td>
                        <td rowspan="@count">@item.Key.eduTypeName</td>
                        <td rowspan="@count">@item.Key.stuTypeName</td>
                        <td rowspan="@count">@item.Key.rs</td>

                        <td rowspan="@teamcount">@{ Write(lists[0].y_team % 2 == 1 ? "上" : "下"); }</td>
                        <td>@lists[0].courseName</td>
                    </tr>

                            for (int i = 1; i < count; i++)
                            {
                                if (i == teamcount)
                                {
                                    <tr>
                                        <td rowspan="@secordcount">@{ Write(lists[i].y_team % 2 == 1 ? "上" : "下"); }</td>
                                        <td>@lists[i].courseName</td>
                                    </tr>
                                            }
                                            else
                                            {
                                                <tr>
                                                    <td>@lists[i].courseName</td>
                                                </tr>
                                                    }

                                                }
                                            }
            </table>
        </div>
    </div>
    <script>
    $(document).ready(function() {
        $("#uploadsub").click(function() {
            $(".show-c").css('display', 'none');
            $(".upload").click(function() {
                $(this).parents(".nava1").find(".show-bg").stop().fadeTo(500, 1);
                $(this).parents(".nava1").find(".show-c").css("display", "block");
            });
            $(".close").click(function() {
                $(this).parents(".nava1").find(".show-bg").css('display', 'none');
                $(this).parents(".nava1").find(".show-c").css("display", "none");
            });
        });

        if ($('#EnrollYear2').find("option").eq(0).val() == 0) {
            $('#EnrollYear2').find("option").eq(0).remove();  //除去年度中的全部
        }
    });

    function ExcelDown() {
        $.ajax({
            url: '@Url.Action("DownIsMainCoursePlan", "TeaPlan")',
            data: { year: '@year',school:'@school' },
            type: 'post',
            dataType: 'json',
            success: function (data) {
                if (data.IsOk) {
                    window.open(data.Message);
                } else {
                    console.log(data.Message);
                }
            }

        });
    }
        function yearchangeComple() {  //年度改变回调
            SearchSchool();
        }
        function SearchSchool() {
            var year = $('#EnrollYear').val();
            //$('#SubSchool').attr("disabled", true);
            $('#SubSchool').combobox("disable");
            $.ajax({
                url: '@Url.Action("GetSchoolByYear_Stu", "Helper")',
                data: {
                    year: year
                },
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    //$('#SubSchool').bindData(data, 'y_subSchoolId', 'schoolName');
                    //$('#SubSchool').attr("disabled", false);
                    LoadCombobox('#SubSchool', data, 'y_subSchoolId', 'schoolName');
                },
                error: function () {
                    //$('#SubSchool').attr("disabled", false);
                    $('#SubSchool').combobox("enable");
                }
            });
        }
        //EasyUi
        $(document).ready(function () {
            //设置面板长度
            $('select.easyui-combobox').attr("panelHeight", "400");
            //设置面板宽度
            $('select.easyui-combobox').css("width", "250px");

            easyloader.css = false;

            easyloader.load('combobox', function () { // 加载指定模块
                $('select.easyui-combobox').combobox({
                    onHidePanel: function () {
                        if (isNaN($(this).combobox('getValue'))) {
                            var $this = $(this);

                            var valueField = $this.combobox('options').valueField;
                            var textField = $this.combobox('options').textField;

                            var text = $this.combobox('getValue');
                            var data = $this.combobox('getData');

                            $.each(data, function (i, n) {
                                if (eval('n.' + textField).indexOf(text) >= 0) {
                                    $this.combobox('setValue', eval('n.' + valueField));
                                    return false;
                                }
                            });

                            if (isNaN($(this).combobox('getValue'))) {
                                $this.combobox('setValue', 0);
                            }

                        }
                    }
                });

                $(".combo").click(function() {
                    if ($(this).prev().combobox("panel").is(":visible")) {
                        //$(this).prev().combobox("hidePanel");
                    } else {
                        $(this).prev().combobox("showPanel");
                    }
                });


            });

            easyloader.onLoad = function (name){
                if (name.length == 1 &&name[0] == "combobox") {

                    //赋初始值 (赋值时会触发onchange事件)
                    $('#SubSchool').combobox('setValue', @school);
                    }
            }
        });
    </script>
    @Html.Action("Foot", "AdminBase")
</body>
</html>

IYun/Views/TeaPlan/SchoolCoursePlan.cshtml
@{
    Layout = null;
}
@using System.Configuration
@using IYun.Models
@using IYun.Object
@model List<IYun.Controllers.ControllerObject.CoursePlanDto>
@{
    Layout = null;
    var modulePowers = ViewBag.modulePowers as List<ModulePower>;
    modulePowers = modulePowers ?? new List<ModulePower>();
    var year = Convert.ToInt32(ViewData["year"]);
    var school = Convert.ToInt32(ViewData["school"]);

    var list = Model.GroupBy(u => new
    {
        u.y_year,
        u.majorName,
        u.stuTypeName,
        u.eduTypeName,
        u.rs
    }).ToList();

}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ConfigurationManager.AppSettings["SchoolTitle"]</title>
    <link rel="stylesheet" href="~/Content/manage/style/css.css?v=1" type="text/css" /><!-- 全部样式 -->
    <link rel="stylesheet" href="~/Content/manage/style/reset.css" type="text/css" /><!-- 重置样式 -->
    <link href="~/Content/manage/style/pic.css" rel="stylesheet" type="text/css" /><!-- 相册样式 -->
    <!--[ifltIE9]>
    <script type="text/javascript" src="js/html5shiv.js"></script>
    <![endif]-->
    <!-- 使得ie678支持HTML5标签 -->
    <!--[ifltIE10]> 
    <script type="text/javascript" src="~/Content/manage/js/PIE.js"></script>
    <![endif]-->
    <!-- 使得ie6789支持CSS3样式 -->
    @*<script src="~/Content/manage/js/jquery-1.7.1.min.js" type="text/javascript"></script>*@
    <script src="~/Content/js/jquery-1.9.1.min.js"></script>
    <script src="~/Content/manage/js/jquery.nicescroll.js" type="text/javascript"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/respond.js"></script>
    <script src="~/Content/manage/ComboboxBind.js?v=1"></script>  
    <script src="~/Content/EasyUI/easyloader.js"></script>
    <link href="~/Content/EasyUI/combo.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/combobox.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/panel.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/textbox.css" rel="stylesheet" />
    <script type="text/javascript">
        //EvPNG.fix('div, ul, img, li, input');

        $(function() {
            if (window.PIE) {
                $('.rounded').each(function() {
                    PIE.attach(this);
                });
            }
            //使得ie6789支持CSS3样式

        });

    </script>
    <style>
        .xx-table td {
            border: 1px solid #e9e9e9;
        }
    </style>
</head>

<body>
    @Html.Action("Top", "AdminBase")
    <div class="main center">
        <div id="main-tl">
            <div class="left-t">教务管理</div>
            <div class="left-c">
                @{
                    foreach (var modulePower in modulePowers)
                    {
                        if (modulePower.y_url.ToLower() == "/TeaPlan/SchoolCoursePlan".ToLower())
                        {
                            <a class="on" href="@modulePower.y_url">@modulePower.y_moudleName</a>
                        }
                        else
                        {
                            <a href="@modulePower.y_url">@modulePower.y_moudleName</a>
                        }
                    }
                }
            </div>
        </div>
        <div id="main-tr">
            <form action="@Url.Action("SchoolCoursePlan","TeaPlan")" id="searchForm" method="post">
                <div class="cli">
                    <div class="zc-inn">
                        <span style="margin-left: 20px;">年份</span>
                        @Html.Action("EnrollYear2", "Helper", new HelperParameterM {style = "width:200px;font-size: 18px;", index = year})
                    </div>
                    <div class="zc-inn">
                        <span style="margin-left: 20px;">函授站</span>
                        @Html.Action("SubSchool", "Helper", new HelperParameterM { className = "easyui-combobox" })
                    </div>
                    <div class="zc-head">
                        <input style="margin-top: 10px; height: 32px; line-height: 30px; float: right" class="cx-sub" type="button" onclick="ExcelDown()" value="导出" />
                        <input style="margin-top: 10px; height: 32px; line-height: 30px; float: right" class="cx-sub" type="submit" value="查找" />
                    </div>
                </div>
            </form>

            <table class="xx-table ydong-tab">
                <tr>
                    <th>年份</th>
                    <th>专业名</th>
                    <th>层次</th>
                    <th>形式</th>
                    <th>人数</th>
                    <th>学期</th>
                    <th>课程</th>
                </tr>

                @foreach (var item in list)
                {
                    var lists = item.ToList();
                    var count = item.Count();
                    var teamcount = lists.Count(u => u.y_team == lists[0].y_team);
                    var secordcount = count - teamcount;

                    <tr>
                        <td rowspan="@count">@item.Key.y_year</td>
                        <td rowspan="@count">@item.Key.majorName</td>
                        <td rowspan="@count">@item.Key.eduTypeName</td>
                        <td rowspan="@count">@item.Key.stuTypeName</td>
                        <td rowspan="@count">@item.Key.rs</td>

                        <td rowspan="@teamcount">@{ Write(lists[0].y_team%2 == 1 ? "上" : "下"); }</td>
                        <td>@lists[0].courseName</td>
                    </tr>

                    for (int i = 1; i < count; i++)
                    {
                        if (i == teamcount)
                        {
                            <tr>
                                <td rowspan="@secordcount">@{ Write(lists[i].y_team%2 == 1 ? "上" : "下"); }</td>
                                <td>@lists[i].courseName</td>
                            </tr>
                        }
                        else
                        {
                            <tr>
                                <td>@lists[i].courseName</td>
                            </tr>
                        }

                    }
                }
            </table>
        </div>
    </div>
    <script>
    $(document).ready(function() {
        $("#uploadsub").click(function() {
            $(".show-c").css('display', 'none');
            $(".upload").click(function() {
                $(this).parents(".nava1").find(".show-bg").stop().fadeTo(500, 1);
                $(this).parents(".nava1").find(".show-c").css("display", "block");
            });
            $(".close").click(function() {
                $(this).parents(".nava1").find(".show-bg").css('display', 'none');
                $(this).parents(".nava1").find(".show-c").css("display", "none");
            });
        });

        if ($('#EnrollYear2').find("option").eq(0).val() == 0) {
            $('#EnrollYear2').find("option").eq(0).remove();  //除去年度中的全部
        }
    });

    function ExcelDown() {
        $.ajax({
            url: '@Url.Action("SchoolCoursePlanDown", "TeaPlan")',
            data: { year: '@year',school:'@school' },
            type: 'post',
            dataType: 'json',
            success: function (data) {
                if (data.IsOk) {
                    window.open(data.Message);
                } else {
                    console.log(data.Message);
                }
            }

        });
    }
        function yearchangeComple() {  //年度改变回调
            SearchSchool();
        }
        function SearchSchool() {
            var year = $('#EnrollYear').val();
            //$('#SubSchool').attr("disabled", true);
            $('#SubSchool').combobox("disable");
            $.ajax({
                url: '@Url.Action("GetSchoolByYear_Stu", "Helper")',
                data: {
                    year: year
                },
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    //$('#SubSchool').bindData(data, 'y_subSchoolId', 'schoolName');
                    //$('#SubSchool').attr("disabled", false);
                    LoadCombobox('#SubSchool', data, 'y_subSchoolId', 'schoolName');
                },
                error: function () {
                    //$('#SubSchool').attr("disabled", false);
                    $('#SubSchool').combobox("enable");
                }
            });
        }
        //EasyUi
        $(document).ready(function () {
            //设置面板长度
            $('select.easyui-combobox').attr("panelHeight", "400");
            //设置面板宽度
            $('select.easyui-combobox').css("width", "250px");

            easyloader.css = false;

            easyloader.load('combobox', function () { // 加载指定模块
                $('select.easyui-combobox').combobox({
                    onHidePanel: function () {
                        if (isNaN($(this).combobox('getValue'))) {
                            var $this = $(this);

                            var valueField = $this.combobox('options').valueField;
                            var textField = $this.combobox('options').textField;

                            var text = $this.combobox('getValue');
                            var data = $this.combobox('getData');

                            $.each(data, function (i, n) {
                                if (eval('n.' + textField).indexOf(text) >= 0) {
                                    $this.combobox('setValue', eval('n.' + valueField));
                                    return false;
                                }
                            });

                            if (isNaN($(this).combobox('getValue'))) {
                                $this.combobox('setValue', 0);
                            }

                        }
                    }
                });

                $(".combo").click(function() {
                    if ($(this).prev().combobox("panel").is(":visible")) {
                        //$(this).prev().combobox("hidePanel");
                    } else {
                        $(this).prev().combobox("showPanel");
                    }
                });

          
            });

            easyloader.onLoad = function (name){
                if (name.length == 1 &&name[0] == "combobox") {
                    
                    //赋初始值 (赋值时会触发onchange事件)
                    $('#SubSchool').combobox('setValue', @school);
                    }
            }
        });
    </script>
    @Html.Action("Foot", "AdminBase")
</body>
</html>