IYun/Controllers/ScoreController.cs
using IYun.Common;
using IYun.Controllers.ControllerObject;
using IYun.Dal;
using IYun.Models;
using IYun.Object;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using NPOI.HSSF.UserModel;
using NPOI.HSSF.Util;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace IYun.Controllers
{
    /// <summary>
    /// c成绩管理
    /// </summary>
    public class ScoreController : AdminBaseController
    {
        private YD_Edu_ScoreDal _scoreDal = new YD_Edu_ScoreDal();

        /// 成绩列表页--弃用
        public ActionResult Score(int id = 1)
        {
            #region “成绩列表”权限验证

            var power = SafePowerPage("/Score/Score");
            if (!IsLogin())
            {
                return Redirect("/AdminBase/Index");
            }
            if (power == null || power.y_menu == (int)PowerState.Disable)
            {
                //var reurl = Request.UrlReferrer.ToString();
                var reurl = "/AdminBase/Index";
                return Content("<script>alert('没有权限');window.location.href='" + reurl + "'</script>");
            }

            #endregion

            ViewBag.power = power;
            using (var yunEntities = new IYunEntities())
            {
                var ySubSchoolIdStr = Request["SubSchool"];
                var yMajorIdStr = Request["MajorLibrary"];
                var yStuNum = Request["y_stuNum"];
                var name = Request["name"];
                IQueryable<VW_ScoreFirst> list = yunEntities.VW_ScoreFirst.OrderByDescending(u => u.y_stuId);
                if (!string.IsNullOrWhiteSpace(name))
                {
                    list = list.Where(u => u.y_stuName.Contains(name));
                }
                if (!string.IsNullOrWhiteSpace(yStuNum))
                {
                    list = list.Where(u => u.y_stuNum.Contains(yStuNum));
                }
                if (!string.IsNullOrWhiteSpace(ySubSchoolIdStr) && !ySubSchoolIdStr.Equals("0"))
                {
                    var ySubSchoolId = Convert.ToInt32(ySubSchoolIdStr);
                    list = list.Where(u => u.y_subSchoolId == ySubSchoolId);
                }
                if (!string.IsNullOrWhiteSpace(yMajorIdStr) && !yMajorIdStr.Equals("0"))
                {
                    var yMajorId = Convert.ToInt32(yMajorIdStr);
                    list = list.Where(u => u.y_majorId == yMajorId);
                }
                if (YdAdminRoleId == 4 || YdAdminRoleId == 5 || YdAdminRoleId == 9)
                {

                    var subSchoolIds = yunEntities.YD_Sys_AdminSubLink.Where(u => u.y_adminId == YdAdminId).Select(u => u.y_subSchoolId);
                    var stuInfos =
                        yunEntities.VW_StuInfo.Where(u => u.y_subSchoolId.HasValue && subSchoolIds.Contains(u.y_subSchoolId.Value))
                            .DistinctBy(u => new { u.y_majorId, u.y_subSchoolId }).Select(u => u.y_majorId)
                            .ToList();
                    list = list.Where(u => u.y_majorId.HasValue && stuInfos.Contains(u.y_majorId.Value));
                }

                var dbLogList = list.ToPagedList(id, 15); //id为pageindex   15 为pagesize;
                ViewBag.modulePowers = GetChildModulePower(yunEntities, 4); //根据父栏目ID获取兄弟栏目
                ViewBag.adminrole = YdAdminRoleId;
                if (Request.IsAjaxRequest())
                    return PartialView("ScoreList", dbLogList);
                return View(dbLogList);
            }
        }

        /// 查看学生个人课程成绩详情
        public ActionResult ScoreFirst(int? id)
        {
            #region “成绩列表”权限验证

            var power = SafePowerPage("/Score/Score");
            if (!IsLogin())
            {
                return Redirect("/AdminBase/Index");
            }
            if (power == null || power.y_menu == (int)PowerState.Disable)
            {
                //var reurl = Request.UrlReferrer.ToString();
                var reurl = "/AdminBase/Index";
                return Content("<script>alert('没有权限');window.location.href='" + reurl + "'</script>");
            }

            #endregion

            ViewBag.power = power;
            ViewBag.role = YdAdminRoleId;
            using (var yunEntities = new IYunEntities())
            {
                var ySubSchoolIdStr = Request["SubSchool"];
                var yTermStr = Request["y_term"];
                var yCourseIdStr = Request["Course"];
                var name = Request["name"];
                IQueryable<VW_Score> list = yunEntities.VW_Score.OrderBy(u => u.y_term).Where(u => u.y_stuId == id);
                if (!string.IsNullOrWhiteSpace(yCourseIdStr) && !yCourseIdStr.Equals("0")) //课程
                {
                    var yCourseId = Convert.ToInt32(yCourseIdStr);
                    list = list.Where(u => u.y_courseId == yCourseId);
                    ViewBag.course = yCourseId;
                }
                if (!string.IsNullOrWhiteSpace(yTermStr) && !yTermStr.Equals("0"))
                {
                    var yTerm = Convert.ToInt32(yTermStr);
                    list = list.Where(u => u.y_term == yTerm);
                    ViewBag.term = yTerm;
                }
                if (YdAdminRoleId == 4 || YdAdminRoleId == 5 || YdAdminRoleId == 9)
                {
                    var subSchoolIds = yunEntities.YD_Sys_AdminSubLink.Where(u => u.y_adminId == YdAdminId).Select(u => u.y_subSchoolId);
                    var stuInfos = yunEntities.VW_StuInfo.Where(u => u.y_subSchoolId.HasValue && subSchoolIds.Contains(u.y_subSchoolId.Value))
                        .DistinctBy(u => new { u.y_majorId, u.y_subSchoolId }).Select(U => U.y_majorId).ToList();

                    list = list.Where(u => u.y_majorId.HasValue && stuInfos.Contains(u.y_majorId.Value));
                }
                ViewBag.modulePowers = GetChildModulePower(yunEntities, 4); //根据父栏目ID获取兄弟栏目
                var model = list.ToList();
                ViewBag.stuid = id;
                return View(model);
            }
        }

        /// 成绩列表页--弃用
        public ActionResult DownloadScore()
        {
            #region “成绩列表”权限验证

            var power = SafePowerPage("/Score/Score");
            if (!IsLogin())
            {
                return Redirect("/AdminBase/Index");
            }
            if (power == null || power.y_select == (int)PowerState.Disable)
            {
                var reurl = Request.UrlReferrer.ToString();
                return Content("<script>alert('没有权限');window.location.href='" + reurl + "'</script>");
            }

            #endregion

            ViewBag.power = power;
            using (var yunEntities = new IYunEntities())
            {
                var ySubSchoolIdStr = Request["SubSchool"];
                var yMajorIdStr = Request["majorlihidden"];
                var yTermStr = Request["y_term"];
                var yStuNum = Request["y_stuNum"];

                IQueryable<VW_Score> list = yunEntities.VW_Score.OrderByDescending(u => u.id);

                if (!string.IsNullOrWhiteSpace(yStuNum))
                {
                    list = list.Where(u => u.y_stuNum.Contains(yStuNum));
                }

                if (!string.IsNullOrWhiteSpace(yTermStr) && !yTermStr.Equals("0"))
                {
                    var yTerm = Convert.ToInt32(yTermStr);
                    list = list.Where(u => u.y_term == yTerm);
                }
                if (!string.IsNullOrWhiteSpace(ySubSchoolIdStr) && !ySubSchoolIdStr.Equals("0"))
                {
                    //var y_subSchoolId = Convert.ToInt32(y_subSchoolIdStr);
                    list = list.Where(u => u.schoolName == ySubSchoolIdStr);
                }
                if (!string.IsNullOrWhiteSpace(yMajorIdStr) && !yMajorIdStr.Equals("0"))
                {
                    var yMajorId = Convert.ToInt32(yMajorIdStr);
                    list = list.Where(u => u.y_majorId == yMajorId);
                }
                var model =
                    FileHelper.ToDataTable(
                        list.Select(
                            u =>
                                new
                                {
                                    u.y_stuName,
                                    u.y_sex,
                                    u.y_stuNum,
                                    u.y_examNum,
                                    u.majorLibraryName,
                                    u.eduTypeName,
                                    u.stuTypeName,
                                    u.schoolName,
                                    u.y_inYear,
                                    u.y_normalScore,
                                    u.y_termScore,
                                    u.y_totalScore
                                }).ToList());

                var dirPath = Server.MapPath("~/File/Dowon"); //todo:改变
                if (!Directory.Exists(dirPath)) //todo:改变
                {
                    Directory.CreateDirectory(dirPath); //todo:改变
                }
                var filename1 = "/学生成绩表" + ".xls"; //todo:改变
                var fileName3 = dirPath + filename1; //todo:改变


                //var filename1 = "File/Dowon/学生成绩表" + Guid.NewGuid() + ".xls";
                //var fileName2 = "~/" + filename1;
                //var fileName3 = Server.MapPath(fileName2);
                using (var excelHelper = new ExcelHelper(fileName3))
                {
                    var ht = new Hashtable
                    {
                        {"y_stuName", "姓名"},
                        {"y_sex", "性别"},
                        {"y_stuNum", "学号"},

IYun/Views/Score/PrintScore.cshtml
@using System.Configuration
@using IYun.Models
@using IYun.Object
@{
    Layout = null;
    var ydAdmin = (YD_Sys_Admin)ViewBag.ydAdmin;
}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ConfigurationManager.AppSettings["SchoolTitle"]</title>
    <link rel="stylesheet" href="~/Content/manage/style/css.css" type="text/css" /><!-- 全部样式 -->
    <link rel="stylesheet" href="~/Content/manage/style/reset.css" type="text/css" /><!-- 重置样式 -->
    <link href="~/Content/manage/style/pic.css" rel="stylesheet" type="text/css" /><!-- 相册样式 -->
    <!--[ifltIE9]>
    <script type="text/javascript" src="js/html5shiv.js"></script>
    <![endif]-->
    <!-- 使得ie678支持HTML5标签 -->
    <!--[ifltIE10]> 
    <script type="text/javascript" src="~/Content/manage/js/PIE.js"></script>
    <![endif]-->
    <!-- 使得ie6789支持CSS3样式 -->
    <script src="~/Content/manage/js/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="~/Content/manage/js/jquery.nicescroll.js" type="text/javascript"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/respond.js"></script>
    <script src="~/Scripts/MvcPager.js"></script>
    <link href="~/Content/kindeditor-4.1.10/themes/default/default.css" rel="stylesheet" />
    <script src="~/Content/kindeditor-4.1.10/kindeditor-min.js"></script>
    <script src="~/Content/kindeditor-4.1.10/lang/zh_CN.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Content/IYun/js/jquery.editable-select.min.js"></script>
    <link href="~/Content/IYun/style/jquery.editable-select.min.css" rel="stylesheet" />
    <script type="text/javascript">
        //EvPNG.fix('div, ul, img, li, input');

        $(function () {
            if (window.PIE) {
                $('.rounded').each(function () {
                    PIE.attach(this);
                });
            }
            //使得ie6789支持CSS3样式

        });

        KindEditor.ready(function (K) {
            var editor = K.editor({
                allowFileManager: true,
                uploadJson: '../../Content/kindeditor-4.1.10/asp.net/excelUpload.ashx',//文件处理程序
                fileManagerJson: '../../Content/kindeditor-4.1.10/asp.net/file_manager_json.ashx',
                imageSizeLimit: '10MB',
                imageUploadLimit: 10
            });
            K('#insertfile').click(function () {
                editor.loadPlugin('insertfile', function () {
                    editor.plugin.fileDialog({
                        fileUrl: K('#url').val(),
                        clickFn: function (url, title) {
                            K('#url').val(url);
                            editor.hideDialog();
                        }
                    });
                });
            });

        });
        function SendLoginSuccess(data) {
            if (data == "ok") {
                window.location.href = "/Student/StudentInfo";
            } else {
                changeCode();
                alert(data);
            }
        }
    </script>
</head>

<body>
    @Html.Action("Top", "AdminBase")
    <div class="main center">
        <div class="inmain2">
            @using (Ajax.BeginForm("PrintMajorScore", "Score", new { }, new AjaxOptions { OnSuccess = "SendLoginSuccess" }, new { id = "searchForm" }))
            {
                <div class="zc-head">
                    <div class="zc-inn">
                        <span>学习中心</span>
                        @Html.Action("SubSchool", "Helper", new HelperParameterM { style = "width:260px;", name = "y_subSchoolId" })
                    </div>
                    <div class="zc-inn">
                        <span>学期</span>
                        <select class="cx-sel" name="y_term" style="width:130px;">
                            <option value="0">全部</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                    </div>
                    <div class="zc-inn">
                        <span>专业</span>
                        @Html.Action("Major", "Helper", new HelperParameterM { style = "width:150px;", name = "y_majorId" })
                    </div>

                    <div class="zc-inn">
                        <input style="margin-top:0px; height:32px; line-height:30px;" type="submit" class="cx-sub" value="查找" />
                    </div>
                    <a style="height:32px; line-height:30px; float:right; width:80px; margin:12px 35px 0 0;" class="zc-sub" href="javascript:myPrint(document.getElementById('print'))">打印</a>


                </div>
            }
            <div id="print">
                <div>
                    <p>2015成教院 函授 专升本 地理科学成绩单 </p>
                </div>
                <table>
                    <tr>
                        <td>
                            姓名
                        </td>
                        <td>
                            学号
                        </td>
                        <td>第一学期</td>
                        <td>第二学期</td>
                        <td>第三学期</td>
                        <td>第四学期</td>
                        <td>第五学期</td>
                        <td>第六学期</td>
                        <td>第七学期</td>
                        <td>第八学期</td>
                        <td>第九学期</td>
                        <td>第十学期</td>
                    </tr>
                    <tr>
                        <td>科目一</td>
                        <td>科目二</td>
                        <td>科目三</td>
                        <td>科目一</td>
                        <td>科目二</td>
                        <td>科目三</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    @Html.Action("Foot", "AdminBase")
</body>
</html>
<script>
    function myPrint(obj) {
        var newWindow = window.open("/Score/printscore", "_blank");//打印窗口要换成页面的url
        var docStr = obj.innerHTML;
        newWindow.document.write(docStr);
        newWindow.document.close();
        newWindow.print();
        newWindow.close();
    }
    function loadScore() {
        $.ajax({
            type: "POST",
            url: "/Score/DownloadScore",
            data: form2Json("searchForm"),
            success: function (data) {
                if (data == "no") {
                    alert("错误");
                } else {
                    window.location.href = data;
                }
            }
        });
    }
    function form2Json(id) {
        var arr = $("#" + id).serializeArray();
        var jsonStr = "";
        jsonStr += '{';
        for (var i = 0; i < arr.length; i++) {
            jsonStr += '"' + arr[i].name + '":"' + arr[i].value + '",';
        }
        jsonStr = jsonStr.substring(0, (jsonStr.length - 1));
        jsonStr += '}';
        var json = JSON.parse(jsonStr);
        return json;
    }
</script>

IYun/Views/Score/RecordScoreMajorTable.cshtml
@using Webdiyer.WebControls.Mvc
@using IYun.Models;
@model PagedList<VW_StuInfo>

<table class="xx-table ydong-tab">
    <tr>
        <th>年度</th>
        <th>专业名称</th>
        <th>操作</th>
    </tr>
    @{
        foreach (var ydSysAdmin in Model)
        {
            <tr>
                <td>@ViewData["year"]</td>
                <td>@ydSysAdmin.majorName</td>
                <td><a class="bfont2" href="/Score/RecordScoreCourse/?year=@ViewData["year"]&subId=@ViewData["subId"]&majorId=@ydSysAdmin.y_majorId">选择科目</a></td>
            </tr>
        }
    }
</table>

IYun/Views/Score/RecordScoreSubTable.cshtml
@using Webdiyer.WebControls.Mvc
@using IYun.Models;
@model PagedList<YD_Sys_SubSchool>

<table class="xx-table ydong-tab">
    <tr>
        <th>函授站</th>
        <th>函授站代码</th>
        <th>操作</th>
    </tr>
    @{
        foreach (var ydSysAdmin in Model)
        {
            <tr>
                <td>@ydSysAdmin.y_name</td>
                <td>@ydSysAdmin.y_code</td>
                <td><a class="bfont2" href="/Score/RecordScoreMajor/?subId=@ydSysAdmin.id">选择专业</a></td>
            </tr>
        }
    }
</table>

IYun/Views/Score/RecordScoreTable.cshtml
@using Webdiyer.WebControls.Mvc
@using IYun.Models;
@model PagedList<VW_StuInfo>

<table class="xx-table">
    <tr>
        <th style="padding-left:25px; width:180px;">学号</th>
        <th>姓名</th>
        <th>函授站</th>
        <th>专业</th>
        <th>入学年份</th>
        <th>状态</th>
        <th width="60px;">操作</th>
    </tr>

    @foreach (VW_StuInfo student in Model)
    {
        <tr>
            <td style="padding-left:25px;">@student.y_stuNum</td>
            <td>@student.y_name</td>
            <td>@student.schoolName</td>
            <td>@student.majorName</td>
            <td>@student.y_inYear</td>
            <td>@student.stuStateName</td>
            <td><a class="bfont2" target="_blank" href="/Score/StudentScore/@student.id">录分</a></td>
        </tr>
    }
</table>

IYun/Views/Score/ScoreStatistics.cshtml
@{
    Layout = null;
}
@using System.Configuration
@using IYun.Models
@using IYun.Object
@model List<IYun.Controllers.ControllerObject.ScoreStatistics>
@{
    Layout = null;
    var modulePowers = ViewBag.modulePowers as List<ModulePower>;
    modulePowers = modulePowers ?? new List<ModulePower>();

    var year = Convert.ToInt32(ViewData["year"]);
    var school = Convert.ToInt32(ViewData["school"]);
    var major = Convert.ToInt32(ViewData["major"]);
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ConfigurationManager.AppSettings["SchoolTitle"]</title>
    <link rel="stylesheet" href="~/Content/manage/style/css.css" type="text/css" /><!-- 全部样式 -->
    <link rel="stylesheet" href="~/Content/manage/style/reset.css" type="text/css" /><!-- 重置样式 -->
    <link href="~/Content/manage/style/pic.css" rel="stylesheet" type="text/css" /><!-- 相册样式 -->
    <!--[ifltIE9]>
    <script type="text/javascript" src="js/html5shiv.js"></script>
    <![endif]-->
    <!-- 使得ie678支持HTML5标签 -->
    <!--[ifltIE10]> 
    <script type="text/javascript" src="~/Content/manage/js/PIE.js"></script>
    <![endif]-->
    <!-- 使得ie6789支持CSS3样式 -->
    @*<script src="~/Content/manage/js/jquery-1.7.1.min.js" type="text/javascript"></script>*@
    <script src="~/Content/js/jquery-1.9.1.min.js"></script>
    <script src="~/Content/manage/js/jquery.nicescroll.js" type="text/javascript"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/respond.js"></script>
    <script src="~/Content/manage/ComboboxBind.js?v=1"></script>
    <script src="~/Content/EasyUI/easyloader.js"></script>
    <link href="~/Content/EasyUI/combo.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/combobox.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/panel.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/textbox.css" rel="stylesheet" />
    <script type="text/javascript">
        //EvPNG.fix('div, ul, img, li, input');

        $(function () {
            if (window.PIE) {
                $('.rounded').each(function () {
                    PIE.attach(this);
                });
            }
            //使得ie6789支持CSS3样式
        });

    </script>
    <style>
        .xx-table td {
            border: 1px solid #e9e9e9;
        }
    </style>
</head>

<body>
    @Html.Action("Top", "AdminBase")
    <div class="main center">
        <div id="main-tl">
            <div class="left-t">成绩管理</div>
            <div class="left-c">
                @{
                    foreach (var modulePower in modulePowers)
                    {
                        if (modulePower.y_url.ToLower() == "/Score/ScoreStatistics".ToLower())
                        {
                            <a class="on" href="@modulePower.y_url">@modulePower.y_moudleName</a>
                        }
                        else
                        {
                            <a href="@modulePower.y_url">@modulePower.y_moudleName</a>
                        }
                    }
                }
            </div>
        </div>
        <div id="main-tr">
            <form action="@Url.Action("ScoreStatistics","Score")" id="searchForm" method="post">
                <div class="cli">
                    <div class="zc-inn">
                        <span style="margin-left: 20px;">年份</span>
                        @Html.Action("EnrollYear2", "Helper", new HelperParameterM { style = "width:200px;font-size: 18px;", index = year })
                    </div>
                    <div class="zc-inn">
                        <span style="margin-left: 20px;">函授站</span>
                        @Html.Action("SubSchool", "Helper", new HelperParameterM{className= "easyui-combobox"})
                    </div>
                    <div class="zc-inn">
                        <span style="margin-left: 20px;">专业</span>
                        @Html.Action("Major", "Helper", new HelperParameterM {className = "easyui-combobox" })
                    </div>
                    <div class="zc-head">
                        <input style="margin-top: 10px; height: 32px; line-height: 30px; float: right" class="cx-sub" type="submit" value="查找" />
                    </div>
                </div>
            </form>

            <table class="xx-table ydong-tab">
                <tr>
                    <th>函授站</th>
                    <th>专业</th>
                    <th>是否缺失教学计划</th>
                    <th>总数(科目*人数)</th>
                    <th>已录分(科目*人数)</th>
                    <th>已录比例(%)</th>
                    <th>及格数量(科目*人数)</th>
                    <th>及格比例(%)</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.SchoolName</td>
                        <td>@item.MajorName</td>
                        @if (item.IsSetTeaplan)
                        {
                            <td>否</td>
                            <td><a style="color:blue;" href="/Score/ScoreStatistics_Course?Major= @item.MajorId &Year= @year &School= @item.SubSchoolId ">@item.TotalCount</a></td>
                            <td>@item.HasCount</td>
                            <td>@Math.Round((item.HasCount*100d/item.TotalCount), 2)</td>
                            <td>@item.PassCount</td>
                            <td>@Math.Round((item.PassCount * 100d / item.TotalCount), 2)</td>
                        }
                        else
                        {
                            <td style="color: red;">是</td>
                            <td style="color: red;">\</td>
                            <td style="color: red;">\</td>
                            <td style="color: red;">\</td>
                        }
                    </tr>
                }


            </table>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $("#uploadsub").click(function () {
                $(".show-c").css('display', 'none');
                $(".upload").click(function () {
                    $(this).parents(".nava1").find(".show-bg").stop().fadeTo(500, 1);
                    $(this).parents(".nava1").find(".show-c").css("display", "block");
                });
                $(".close").click(function () {
                    $(this).parents(".nava1").find(".show-bg").css('display', 'none');
                    $(this).parents(".nava1").find(".show-c").css("display", "none");
                });
            });

            if ($('#EnrollYear2').find("option").eq(0).val() == 0) {
                $('#EnrollYear2').find("option").eq(0).remove();  //除去年度中的全部
            }
        });

        function yearchangeComple2() {
            SearchMajor();
        }

        function schoolchangeComple() {
            SearchMajor();
        }

        function SearchMajor() {
            var schoolId = $('#SubSchool').combobox('getValue');
            var year = $('#EnrollYear2').val();

            $('#Major').combobox("disable");
            $.ajax({
                url: '@Url.Action("GetMajor_Stu", "Helper")',
                data: {
                    schoolId: schoolId,
                    year: year
                },
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    LoadCombobox('#Major',data,'id','majorName');
                },
                error: function () {
                    $('#Major').combobox("enable");
                }
            });
        }

        //EasyUi
        $(document).ready(function () {
            //设置面板长度
            $('select.easyui-combobox').attr("panelHeight", "400");
            //设置面板宽度
            $('select.easyui-combobox').css("width", "250px");

            easyloader.css = false;

            easyloader.load('combobox', function () { // 加载指定模块
                $('select.easyui-combobox').combobox({
                    onHidePanel: function () {
                        if (isNaN($(this).combobox('getValue'))) {
                            var $this = $(this);

                            var valueField = $this.combobox('options').valueField;
                            var textField = $this.combobox('options').textField;

                            var text = $this.combobox('getValue');
                            var data = $this.combobox('getData');

                            $.each(data, function (i, n) {
                                if (eval('n.' + textField).indexOf(text) >= 0) {
                                    $this.combobox('setValue', eval('n.' + valueField));
                                    return false;
                                }
                            });

                            if (isNaN($(this).combobox('getValue'))) {
                                $this.combobox('setValue', 0);
                            }

                        }
                    }
                });

                $(".combo").click(function() {
                    if ($(this).prev().combobox("panel").is(":visible")) {
                        //$(this).prev().combobox("hidePanel");
                    } else {
                        $(this).prev().combobox("showPanel");
                    }
                });

                //注册联动
                $('#SubSchool').combobox({
                    onChange: function () {
                        if (!isNaN($(this).combobox('getValue'))) {
                            SearchMajor();
                        }
                    }
                });
            });
            easyloader.onLoad = function (name){
                if (name.length == 1 &&name[0] == "combobox") {
                    
                    //赋初始值 (赋值时会触发onchange事件)
                    $('#SubSchool').combobox('setValue', @school);
                    $('#Major').combobox('setValue', @major);
                }
            }
        });

    </script>
    @Html.Action("Foot", "AdminBase")
</body>
</html>