IYun/Controllers/StudentAccountController.cs
using IYun.Common;
using IYun.Controllers.ControllerObject;
using IYun.Dal;
using IYun.Models;
using IYun.Models.Dto;
using IYun.Object;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;

namespace IYun.Controllers
{
    public class StudentAccountController : AdminBaseController
    {

        private readonly YD_Sts_StuStrangeDal _stuStrangeDal = new YD_Sts_StuStrangeDal();
        //
        // GET: /StudentAccount/
        public ActionResult Login()
        {
            return View();
        }
        public int LoginId
        {
            get
            {
                if (Session[KeyValue.stu_id] == null)
                {
                    Session.RemoveAll();
                    Response.Redirect("/AdminBase/Index");
                }

                return Convert.ToInt32(Session[KeyValue.stu_id]);
            }
        }

        public string Admin_Name
        {
            get
            {
                if (Session[KeyValue.Admin_Name] == null)
                {
                    Session.RemoveAll();
                    Response.Redirect("/AdminBase/Index");
                }

                return Session[KeyValue.Admin_Name].ToString();
            }
        }

        #region Login/Logout



        /// <summary>
        /// 退出后台登录
        /// </summary>
        /// <returns></returns>
        public ActionResult Exit1()
        {
            Session.RemoveAll();
            return RedirectToAction("Index", "AdminBase");
        }
        #endregion

        public ActionResult Index1()
        {
            if (!IsLogin())//检查登录
            {
                return Redirect("/AdminBase/Index");//没登录就跳转
            }
            using (var yunEntities = new IYunEntities())
            {
                IQueryable<YD_Edu_News> list = yunEntities.YD_Edu_News.OrderByDescending(u => u.id);//查新闻，降序排列
                var newslist = list.Where(u => u.y_type == 2).Take(8).ToList();//然后是新闻类型分类
                var listedu = list.Where(u => u.y_type == 1).Take(8).ToList();
                var listtixi = list.Where(u => u.y_type == 3).Take(8).ToList();
                var listqita = list.Where(u => u.y_type == 4).Take(8).ToList();
                ViewBag.newslist = newslist;//放入ViewBag
                ViewBag.listedu = listedu;
                ViewBag.listtixi = listtixi;
                ViewBag.listqita = listqita;
                return View();
            }
        }

        /// <summary>
        /// 顶栏
        /// </summary>
        /// <returns></returns>
        public ActionResult Top1()
        {
            if (!IsLogin())
            {
                return RedirectToAction("Login");
            }
            ViewBag.adminName = Admin_Name;
            return PartialView();
        }

        public ActionResult StudentInfo()
        {
            if (!IsLogin())
            {
                Redirect("/AdminBase/Index");
            }
            using (var yunEntities = new IYunEntities())
            {
                const int status = (int)ApprovaState.HadApprova;

                var student = yunEntities.VW_StuInfo.SingleOrDefault(u => u.id == LoginId);
                //获取异动信息
                var strange =
                    yunEntities.VW_Strange.Where(u => u.y_approvalStatus == status)
                        .FirstOrDefault(u => u.y_stuId == LoginId);
                ViewBag.strange = strange;
                ViewData["student"] = student;
            }
            return View();
        }

        public ActionResult EditStudent()
        {

            #region 权限验证
            if (!IsLogin())
            {
                Redirect("/AdminBase/Index");
            }
            #endregion

            using (var yunEntities = new IYunEntities())
            {
                var student = yunEntities.VW_StuInfo.SingleOrDefault(u => u.id == LoginId);
                if (student == null)
                {
                    return RedirectToAction("StudentInfo");
                }
                ViewData["student"] = student;
                ViewBag.subSchoolName = yunEntities.YD_Sys_SubSchool.First(x => x.id == student.y_subSchoolId).y_name;
            }
            return View();
        }

        /// <summary>
        /// 学生信息编辑AJAX
        /// </summary>
        /// <param name="stu">学生信息对象</param>
        /// <returns>处理结果json</returns>
        public string EditStudentInfo(YD_Sts_StuInfo stu)
        {
            #region 权限验证

            if (!IsLogin())
            {
                Redirect("/AdminBase/Index");
            }

            #endregion

            using (var yunEntities = new IYunEntities())
            {
                yunEntities.Configuration.ValidateOnSaveEnabled = false;
                var stus = yunEntities.YD_Sts_StuInfo.FirstOrDefault(u => u.id == stu.id);

                var re = new Hashtable();


                //var msg = _stuInfoDal.EditStuInfoExtended(stu, Request, yunEntities);

                stus.y_sex = stu.y_sex;
                stus.y_birthday = stu.y_birthday;
                stus.y_tel = stu.y_tel;
                stus.y_mail = stu.y_mail;
                stus.y_address = stu.y_address;
                stus.y_img = stu.y_img;
                yunEntities.Entry(stus).State = EntityState.Modified;

                int r = yunEntities.SaveChanges();
                if (r > 0)
                {
                    // LogHelper.DbLog(Convert.ToInt32(Session[KeyValue.Admin_id]),
                    //Session[KeyValue.Admin_Name].ToString(), (int)LogType.Update,
                    // "修改学生，" + ",id：" + stu.id + "姓名，入学年份，身份证号，出生日期，学号，考生号，学籍状态" + stu.y_name + "," + stu.y_inYear + "," + stu.y_cardId + "," + stu.y_birthday + "," + stu.y_stuNum + "," + stu.y_examNum + "," + stu.y_stuStateId);
                    re["msg"] = "修改成功";
                    re["isok"] = true;
                }
                else
                {
                    re["msg"] = "修改失败";
                    re["isok"] = false;
                }
                return JsonConvert.SerializeObject(re);

            }
        }

        /// <summary>
        /// 补录个税抵扣信息
        /// </summary>
        /// <returns></returns>
        public ActionResult SupplementaryTaxInfo()
        {
            if (!IsLogin())
            {
                Redirect("/AdminBase/Index");
            }
            using (var yunEntities = new IYunEntities())
            {
                var student = yunEntities.VW_StuInfo.SingleOrDefault(u => u.id == LoginId);
                ViewBag.stuNum = student.y_stuNum;
                ViewBag.stuName = student.y_name;
                ViewBag.stuCardId = student.y_cardId;
            }
            return View(LoginId);
        }

        [HttpPost]
        public string SupplementaryTax(SupplementaryTaxInput input)
        {
            #region 权限验证

            if (!IsLogin())
            {
                Redirect("/AdminBase/Index");
            }
            var re = new Hashtable();
            #endregion

            using (var yunEntities = new IYunEntities())
            {
                var stu = yunEntities.YD_Sts_StuInfo.FirstOrDefault(u => u.id == input.Id);
                stu.y_IsWorking = (input.IsWorking == true ? 1 : 0);
                stu.y_cardType = input.CardType;
                stu.y_parentCard1 = input.ParentCard1;
                stu.y_parentCard2 = input.ParentCard2;
                stu.y_parentCardType1 = input.ParentCardType1;
                stu.y_parentCardType2 = input.ParentCardType2;
                stu.y_parentName1 = input.ParentName1;
                stu.y_parentName2 = input.ParentName2;
                if(string.IsNullOrEmpty(input.ParentCard1) || string.IsNullOrEmpty(input.ParentCardType1) || string.IsNullOrEmpty(input.ParentName1 ))
                {
                    re["msg"] = "父母或监护人1信息需要填写完整";
                    re["isok"] = false;
                    return JsonConvert.SerializeObject(re);
                }
                if (input.ParentCard1.Length != 18)
                {
                    re["msg"] = "父母或监护人1身份证不为18位";
                    re["isok"] = false;
                    return JsonConvert.SerializeObject(re);
                }
                int r = yunEntities.SaveChanges();
                if (r > 0)
                {
                    re["msg"] = "补录完毕";
                    re["isok"] = true;
                }
                else
                {
                    re["msg"] = "补录失败";
                    re["isok"] = false;
                }
                return JsonConvert.SerializeObject(re);
            }
        }

        public ActionResult TaxInfo()
        {
            if (!IsLogin())
            {
                Redirect("/AdminBase/Index");
            }
            using (var yunEntities = new IYunEntities())
            {
                var student = yunEntities.VW_StuInfo.SingleOrDefault(u => u.id == LoginId);
                if(student.y_IsWorking == null)
                {
                    return Redirect("/StudentAccount/SupplementaryTaxInfo");
                }
                ViewData["student"] = student;
            }
            return View();
        }

        /// <summary>
        /// 缴费信息
        /// </summary>
        /// <returns></returns>
        public ActionResult Payment()
        {
            #region 权限验证
            if (!IsLogin())
            {
                Redirect("/AdminBase/Login");
            }
            #endregion
            using (var yunEntities = new IYunEntities())
            {
                const int isnotdel = (int)YesOrNo.No;
                IQueryable<YD_Fee_StuFeeTb> list =
                    yunEntities.YD_Fee_StuFeeTb.Include(u => u.YD_Sts_StuInfo).

IYun/Views/StudentAccount/Activity.cshtml
@using System.Configuration
@using IYun.Models
@using IYun.Object
@model List<YT_ActivityVideo>
@{
    Layout = null;
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="~/Content/manage/style/css.css" type="text/css" /><!-- 全部样式 -->
    <link rel="stylesheet" href="~/Content/manage/style/reset.css" type="text/css" /><!-- 重置样式 -->
    <link href="~/Content/manage/style/pic.css" rel="stylesheet" type="text/css" /><!-- 相册样式 -->

    <script src="~/Content/manage/js/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="~/Content/manage/js/jquery.nicescroll.js" type="text/javascript"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/respond.js"></script>
    <script src="~/Scripts/MvcPager.js"></script>
</head>

<body>
    @Html.Action("Top1", "StudentAccount")
    <div class="main center">

        <div id="main-tr">
            <table class="xx-table ydong-tab">
                <tr>
                    <th>活动名称</th>
                    <th>活动开始时间</th>
                    <th>活动结束时间</th>
                    <th>直播地址</th>
                </tr>
                @{
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.y_name</td>
                            <td>@item.y_starttime</td>
                            <td>@item.y_endtime</td>
                            <td>@item.y_url</td>
                            <td><a class="bfont2" href="/StudentAccount/LiveVideo/@item.id">进入直播</a></td>
                        </tr>
                    }
                }
            </table>
        </div>
    </div>
    @Html.Action("Foot", "AdminBase")
</body>
</html>

IYun/Views/StudentAccount/GraduationApplyInfo.cshtml
@using System.Configuration
@using IYun.Models
@using IYun.Object
@using IYun.Common
@using Webdiyer.WebControls.Mvc
@model YD_Sts_StuInfo
@{
    Layout = null;
    var xinshenyear = Convert.ToInt32(ConfigurationManager.AppSettings["xinsheng"]);
    var schoolname = ConfigurationManager.AppSettings["SchoolName"];
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ConfigurationManager.AppSettings["SchoolTitle"]</title>
    <link rel="stylesheet" href="~/Content/manage/style/css.css?v=1" type="text/css" /><!-- 全部样式 -->
    <link rel="stylesheet" href="~/Content/manage/style/reset.css" type="text/css" /><!-- 重置样式 -->
    <link href="~/Content/manage/style/pic.css" rel="stylesheet" type="text/css" /><!-- 相册样式 -->
    <!--[ifltIE9]>
    <script type="text/javascript" src="~/Content/manage/js/html5shiv.js"></script>
    <![endif]-->
    <!-- 使得ie678支持HTML5标签 -->
    <!--[ifltIE10]> 
    <script type="text/javascript" src="~/Content/manage/js/PIE.js"></script>
    <![endif]-->
    <!-- 使得ie6789支持CSS3样式 -->
    @*<script src="~/Content/manage/js/jquery-1.7.1.min.js" type="text/javascript"></script>*@
    <script src="~/Content/js/jquery-1.9.1.min.js"></script>
    <script src="~/Content/manage/js/jquery.nicescroll.js" type="text/javascript"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/respond.js"></script>
    <script src="~/Content/manage/ComboboxBind.js?v=1"></script> 
    <script src="~/Content/EasyUI/easyloader.js"></script>
    <link href="~/Content/EasyUI/combo.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/combobox.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/panel.css" rel="stylesheet" />
    <link href="~/Content/EasyUI/textbox.css" rel="stylesheet" />
    <script type="text/javascript">
        //EvPNG.fix('div, ul, img, li, input');

        $(function () {
            if (window.PIE) {
                $('.rounded').each(function () {
                    PIE.attach(this);
                });
            }
            //使得ie6789支持CSS3样式

        });

    </script>
</head>

<body>
    @Html.Action("Top1", "StudentAccount")
    <div class="main center">


        <div id="main-tr">
            <div class="right-nav">
                <form >

                    <div class="zc-head">
                        <a class="cx-sub" href="javascript:enterGrad()" style="margin-top: 10px; height: 32px; line-height: 30px; float: right">申请毕业</a>
                    </div>
                    <div class="show-bg"></div>
                </form>
            </div>

            <div id="loadingDiv" style="display: none">
                <img src="~/Content/images/loading(1).gif" style="margin-top:30px;width: 600px;" />
            </div>
                <table class="xx-table ydong-tab" id="datatable">
                    <tr>
                        <th>学号</th>
                        <th>考生号 </th>
                        <th>姓名</th>
                        <th>专业</th>
                        <th>入学年份</th>
                        <th>是否达到毕业年份</th>
                        <th>是否学年都注册</th>
                        @if (schoolname == ComEnum.SchoolName.JXSFDX.ToString())
                        {
                            <th>成绩是否审核通过</th>
                        }
                        else
                        {
                            <th>是否成绩合格</th>
                        }
                        @if (schoolname != ComEnum.SchoolName.JXSFDX.ToString())
                        {
                            <th>是否有照片</th>
                        }
                        <th>是否允许毕业</th>
                        <th>是否申请毕业</th>
                    </tr>
                    @{

                    <tr>
                        <td >@Model.y_stuNum</td>
                        <td>@Model.y_examNum</td>
                        <td>@Model.y_name</td>
                        <td>@Model.YD_Edu_Major.y_name</td>
                        <td>@Model.y_inYear</td>
                        @if (Model.y_degreeOK == 1)//是否达到毕业年份
                        {
                            <td>是</td>
                        }
                        else if (Model.y_degreeOK == 0)
                        {
                            <td>否</td>
                        }
                        @if (Model.y_applyOK == 1)//是否都年都注册
                        {
                            <td>是</td>
                        }
                        else if (Model.y_applyOK == 0)
                        {
                            <td>否</td>
                        }
                        @if (schoolname == ComEnum.SchoolName.JXSFDX.ToString())
                        {
                            if (Model.y_scoreOk == 1)
                            {
                                <td>是</td>
                            }
                            else
                            {
                                <td>否</td>
                            }
                        }
                        else
                        {
                            if (Model.y_isChangePlan == 1)//是否成绩合格
                            {
                                <td>是</td>
                            }
                            else if (Model.y_isChangePlan == 0)
                            {
                                <td>否</td>
                            }
                        }
                        @if (schoolname != ComEnum.SchoolName.JXSFDX.ToString())
                        {
                            if (Model.y_img != null)//是否有照片
                            {
                                <td>是</td>
                            }
                            else if (Model.y_img == null)
                            {
                                <td>否</td>
                            }
                        }
                        @if (Model.y_isdel == 1)//是否允许毕业
                        {
                            <td>是</td>
                        }
                        else if (Model.y_isdel == 0)
                        {
                            <td>否</td>
                        }
                        @if (Model.y_isgraduate == true)  //是否已申请毕业
                        {
                            <td>已申请</td>
                        }
                        else
                        {
                            <td>未申请</td>
                        }
                    </tr>
                      }
                </table>
            </div>

        </div>
    @Html.Action("Foot", "AdminBase")
    <script>
        function enterGrad() {
            data = {};
            var len = $("#datatable").find("tr").find("td").length;
            if (len == 11) {
                var y_degreeOK = $('#datatable tr:eq(1) td:eq(5)').html();
                var y_applyOK = $('#datatable tr:eq(1) td:eq(6)').html();
                var y_scoreOk = $('#datatable tr:eq(1) td:eq(7)').html();
                var y_img = $('#datatable tr:eq(1) td:eq(8)').html();
                var y_isdel = $('#datatable tr:eq(1) td:eq(9)').html();
                var y_isgraduate = $('#datatable tr:eq(1) td:eq(10)').html();
                if (y_isgraduate == "已申请") {
                    alert("您已经申请毕业，请勿重复申请");
                    return;
                }
                if (y_degreeOK == "否") {
                    alert("您尚未达到毕业年份");
                    return;
                }
                if (y_applyOK == "否") {
                    alert("您学年没有全注册");
                    return;
                }
                if (y_scoreOk == "否") {
                    alert("您没有上传学籍照片");
                    return;
                }
                if (y_isChangePlan == "否") {
                    alert("您还有课程未及格");
                    return;
                }
                if (y_isdel == "是") {
                    $.ajax({
                        type: "post",
                        url: "/StudentAccount/StuGradInfoSome",
                        success: function (data) {
                            if (data == "ok") {
                                alert("上报成功");
                                $("#searchForm").submit();

                            } else {
                                alert(data);
                            }
                            $('#ajaxtable').fadeIn('10');
                            $('#loadingDiv').hide();
                        },
                        error: function () {
                            $('#ajaxtable').fadeIn('10');
                            $('#loadingDiv').hide();
                            alert("未知错误");
                        }
                    });
                }
            }
            else if (len = 10) {
                var y_degreeOK = $('#datatable tr:eq(1) td:eq(5)').html();
                var y_applyOK = $('#datatable tr:eq(1) td:eq(6)').html();
                var y_isChangePlan = $('#datatable tr:eq(1) td:eq(7)').html();
                var y_isdel = $('#datatable tr:eq(1) td:eq(9)').html();
                var y_isgraduate = $('#datatable tr:eq(1) td:eq(10)').html();
                if (y_isgraduate == "已申请") {
                    alert("您已经申请毕业，请勿重复申请");
                    return;
                }
                if (y_degreeOK == "否") {
                    alert("您尚未达到毕业年份");
                    return;
                }
                if (y_applyOK == "否") {
                    alert("您学年没有全注册");
                    return;
                }
                if (y_isChangePlan == "否") {
                    alert("您还有课程未及格");
                    return;
                }
                if (y_isdel == "是") {
                    $.ajax({
                        type: "post",
                        url: "/StudentAccount/StuGradInfoSome",
                        success: function (data) {
                            if (data == "ok") {
                                alert("上报成功");
                                $("#searchForm").submit();

                            } else {
                                alert(data);
                            }
                            $('#ajaxtable').fadeIn('10');
                            $('#loadingDiv').hide();
                        },
                        error: function () {
                            $('#ajaxtable').fadeIn('10');
                            $('#loadingDiv').hide();
                            alert("未知错误");
                        }
                    });
                }
            }
        }
    </script>
</body>
</html>

IYun/Views/StudentAccount/Index1.cshtml
@using System.Configuration
@using IYun.Models
@using IYun.Object
@{
    var newsstu = ViewBag.newslist as List<YD_Edu_News> ?? new List<YD_Edu_News>();
    var newsedu = ViewBag.listedu as List<YD_Edu_News> ?? new List<YD_Edu_News>();
    var newstixi = ViewBag.listtixi as List<YD_Edu_News> ?? new List<YD_Edu_News>();
    var newsqita = ViewBag.listqita as List<YD_Edu_News> ?? new List<YD_Edu_News>();
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ConfigurationManager.AppSettings["SchoolTitle"]</title>
    <link rel="stylesheet" href="~/Content/manage/style/css.css" type="text/css" /><!-- 全部样式 -->
    <link rel="stylesheet" href="~/Content/manage/style/reset.css" type="text/css" /><!-- 重置样式 -->
    <link href="~/Content/manage/style/pic.css" rel="stylesheet" type="text/css" /><!-- 相册样式 -->
    <!--[ifltIE9]>
    <scripttype="text/javascript" src="js/html5shiv.js"></script>
    <![endif]-->
    <!-- 使得ie678支持HTML5标签 -->
    <!--[ifltIE10]> 
    <script type="text/javascript" src="~/Content/manage/js/PIE.js"></script>
    <![endif]-->
    <!-- 使得ie6789支持CSS3样式 -->
    <script src="~/Content/manage/js/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="~/Content/manage/js/jquery.nicescroll.js" type="text/javascript"></script>
    <link href="~/Content/kindeditor-4.1.10/themes/default/default.css" rel="stylesheet" />
    <script src="~/Content/kindeditor-4.1.10/kindeditor-min.js"></script>
    <script src="~/Content/kindeditor-4.1.10/lang/zh_CN.js"></script>


    <link href="~/Content/news/css.css" rel="stylesheet" />
    <link href="~/Content/news/news.css" rel="stylesheet" />
    <link href="~/Content/news/reset.css" rel="stylesheet" />


    <script type="text/javascript">
        //EvPNG.fix('div, ul, img, li, input');

        $(function() {
            if (window.PIE) {
                $('.rounded').each(function() {
                    PIE.attach(this);
                });
            }
            //使得ie6789支持CSS3样式
        });
    </script>
</head>
<body>
    @Html.Action("Top1", "StudentAccount")
    <div class="nn-k1" style="overflow: hidden; margin-top: 40px;">
        <div class="nn-k2">
            <div class="nn-k">
                <div class="nn-bt">学籍新闻<a href="/Edu/News">MORE</a></div>
                <ul class="nn-ul">
                    @{
                        foreach (var news1 in newsstu)
                        {
                            <li style="border-bottom: 1px dashed #cccccc;">
                                <a style="width:350px;display:block;overflow: hidden;   white-space: nowrap;-o-text-overflow: ellipsis;text-overflow: ellipsis;" href="/Edu/NewDes?id=@news1.id">@news1.y_title</a><span>@news1.y_appytime.ToString("yy-MM-dd")</span>
                            </li>
                        }
                    }
                </ul>
            </div>
            <div class="nn-k">
                <div class="nn-bt">教学新闻<a href="/Edu/News">MORE</a></div>
                <ul class="nn-ul">
                    @{
                        foreach (var news1 in newsedu)
                        {
                            <li style="border-bottom: 1px dashed #cccccc;">
                                <a style="width:350px;display:block;overflow: hidden;   white-space: nowrap;-o-text-overflow: ellipsis;text-overflow: ellipsis;" href="/Edu/NewDes?id=@news1.id">@news1.y_title</a>
                                <span>@news1.y_appytime.ToString("yy-MM-dd")</span>
                            </li>
                        }
                    }
                </ul>
            </div>
            <div class="nn-k">
                <div class="nn-bt">提醒新闻<a href="/Edu/News">MORE</a></div>
                <ul class="nn-ul">
                    @{
                        foreach (var news1 in newstixi)
                        {
                            <li style="border-bottom: 1px dashed #cccccc">
                                <a style="width: 350px; display: block; overflow: hidden; white-space: nowrap; -o-text-overflow: ellipsis; text-overflow: ellipsis;" href="/Edu/NewDes?id=@news1.id">@news1.y_title</a>
                                <span>@news1.y_appytime.ToString("yy-MM-dd")</span>
                            </li>
                        }
                    }
                </ul>
            </div>
            <div class="nn-k">
                <div class="nn-bt">其他新闻<a href="/Edu/News">MORE</a></div>
                <ul class="nn-ul">
                    @{
                        foreach (var news1 in newsqita)
                        {
                            <li style="border-bottom: 1px dashed #cccccc">
                                <a style="width: 350px; display: block; overflow: hidden; white-space: nowrap; -o-text-overflow: ellipsis; text-overflow: ellipsis;" href="/Edu/NewDes?id=@news1.id">@news1.y_title</a>
                                <span>@news1.y_appytime.ToString("yy-MM-dd")</span>
                            </li>
                        }
                    }
                </ul>
            </div>

        </div>
    </div>
    @Html.Action("Foot", "AdminBase")

</body>
</html>

IYun/Views/StudentAccount/LiveVideo.cshtml
@using System.Configuration
@using IYun.Models
@using IYun.Object
@model YT_ActivityVideo
@{

}



<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ConfigurationManager.AppSettings["SchoolTitle"]</title>
    <link rel="stylesheet" href="~/Content/manage/style/css.css" type="text/css" /><!-- 全部样式 -->
    <link rel="stylesheet" href="~/Content/manage/style/reset.css" type="text/css" /><!-- 重置样式 -->
    <link href="~/Content/manage/style/pic.css" rel="stylesheet" type="text/css" /><!-- 相册样式 -->
    <meta http-equiv="x-ua-compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="//g.alicdn.com/de/prismplayer/2.7.4/skins/default/aliplayer-min.css" />
    <script type="text/javascript" charset="utf-8" src="//g.alicdn.com/de/prismplayer/2.7.4/aliplayer-min.js"></script>
    <script src="~/Content/js/jquery-1.9.1.min.js"></script>
    <script src="~/Content/manage/js/jquery.nicescroll.js" type="text/javascript"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/respond.js"></script>
    <script src="~/Scripts/MvcPager.js"></script>
    <script src="~/Content/IYun/js/jquery.editable-select.min.js"></script>
    <link href="~/Content/IYun/style/jquery.editable-select.min.css" rel="stylesheet" />
    <script type="text/javascript">
        //EvPNG.fix('div, ul, img, li, input');

        $(function () {
            if (window.PIE) {
                $('.rounded').each(function () {
                    PIE.attach(this);
                });
            }
            //使得ie6789支持CSS3样式

        });

    </script>
</head>
<body>
    @Html.Action("Top1", "StudentAccount")
    <div class="main center">
        <div id="main-tr">
            <div class="tjia">
                <span>@Model.y_name</span>
            </div>
            <div class="prism-player" id="player-con"></div>
            <script>
                var player = new Aliplayer({
                    "id": "player-con",
                    "source": "@Model.y_url",
                    "width": "100%",
                    "height": "1000px",
                    "autoplay": true,
                    "isLive": true,
                    "rePlay": false,
                    "playsinline": true,
                    "preload": true,
                    "controlBarVisibility": "hover",
                    "useH5Prism": true
                }, function (player) {
                    console.log("播放器创建了。");
                }
                );
            </script>
        </div>
    </div>
    @Html.Action("Foot", "AdminBase")


</body>

</html>